### ISSUE TITLE
Update README and Makefile

### ISSUE THREAD

**Issue by terasum** [hyperledger/fabric-gateway#258]
When I follow the README instruction, and running `make build-go`, it raised: 

```
go build -o bin/gateway cmd/gateway/*.go
malformed import path "cmd/gateway/*.go": invalid char '*'
make: *** [build-go] Error 1
```

Then I found that the cmd is not contained in the repo, so is there something wrong?

**Comment by bestbeforetoday** [comment]
Thank you for flagging up this issue. The README (and make target) is out of date. This is a relic of much earlier in the development of Fabric Gateway when a stand-alone process was used to prototype the server-side Gateway gRPC service. Now this service is embedded directly in the v2.4 Fabric peer. The README and Makefile both need some clean-up so we can use this issue to drive that.

The README provides information for setting up a development environment in order to contribute to the Fabric Gateway client API codebase. For usage of the API in client application, refer to the user documentation:

https://hyperledger.github.io/fabric-gateway/

In particular, the [samples](https://github.com/hyperledger/fabric-gateway/blob/main/samples/README.md) provide examples and instructions for developing and running a client application using the Fabric Gateway API.
