### ISSUE TITLE
Expectations if a gateway peer is restarted for submit transactions

### ISSUE THREAD

**Issue by davidkel** [hyperledger/fabric-gateway#269]
A client does not have to recreate a grpc connection or gateway to cater for a gateway peer terminating and restarting (note this does not take into account talking to a peer through an ALB which may create a different connectivity behaviour), nor should a well designed client applicaton require restarting however the client application should expect certain errors when the peer goes down. 
In our testing we see
```
"Failed","message":"14 UNAVAILABLE: Connection dropped"
```
and
```
"Failed","message":"1 CANCELLED: Call cancelled"}
```
occuring when the gateway peer terminates

When the gateway peer is restarted, even though it will accept requests to endorse you could see the following error

```
"14 UNAVAILABLE: no combination of peers can be derived which satisfy the endorsement policy: no peer combination can satisfy the endorsement policy"
```
These stop after about 1 second in our tests as the gateway peer rediscovers the available peers. This implies that a gateway peer isn't instantly available to process requests even though it accepts requests (potential for enhancement ????)
This doesn't happen all the time due to delays in the client polling for a ready connection and possibly how fast the peer creates it's knowledge of endorsing peers

We could recommend a client make use of the waitForReady api in their grpc connection. This provides a simple api to determine if there is an actual connection to the gateway peer and can be used in a polling fashion to wait until the gateway peer has started and the connection is restored. This of course is no indication that the peer is ready to accept requests and if you don't do this then you will get an error trying to submit the request (as expected as the peer is down). In our testing this proved to be a nice way to wait before sending submit requests but of course doesn't help with the gateway peer not being ready to process the request due to discovering the network

**Comment by bestbeforetoday** [comment]
If some service is temporarily down — either the Gateway peer or another Node it’s trying to reach — then a gRPC UNAVAILABLE seems like exactly the right behaviour, and the client can retry, perhaps with some backoff. I don’t see anything obvious to improve on.

The use of wait-for-ready at the client end just means the client should wait for the gRPC connection to the Gateway to re-establish if it’s currently in a failed state rather than failing fast. Other than just modifying that one aspect of behaviour, I don’t see how it addresses the overall scenario that some service in the network is not currently available.

I guess the use of wait-for-ready for Gateway peer connections to other nodes might slightly change the client-observable behaviour. Whether any behavioural change is desirable, I'm not sure. gRPC defaults to fail-fast by design.
