### ISSUE TITLE
Gateway can't connect to peer at first, connects after some retries

### ISSUE THREAD

**Issue by isrand** [hyperledger/fabric-gateway#488]
Hello all,

We are currently developing an application leveraging the fabric-gateway NPM package in a network running v2.4.6 with 3 orderers, 3 organizations, 1 peer per organization, and 1 NodeJS server wrapping the fabric-gateway per organization.

We are facing an issue by which our server can't reach a peer at first when sending an invoke request, but after some retries it ends up working. We are getting a gRPC error code 14:

```
EndorseError: 14 UNAVAILABLE: No connection established
```

We are creating a Fabric Gateway using this package by doing the following:

```
public async createGateway(blockchainIdentity: Readonly<BlockchainIdentity>, connectionProfile: Readonly<ConnectionProfile>): Promise<Gateway> {
    await this.identityService.createAndSetBlockchainIdentity(blockchainIdentity, connectionProfile); // gets the identity from the wallet as enrolled through the Fabric CA...
    const client: grpc.Client = await this.getGrpcConnection();
    const identity: Identity = await this.identityService.getGatewayIdentity(connectionProfile.client.organization, blockchainIdentity.username);
    const signer: Signer = await this.signerService.getSigner(connectionProfile.client.organization, blockchainIdentity.username);

    return connect({
      client: client,
      identity: identity,
      signer: signer
    });
}

private async getGrpcConnection(): Promise<grpc.Client> {
    const tlsRootCertificate = await new File(Path.toPeerTLSCertificate).getAsBuffer();
    const tlsCredentials = grpc.credentials.createSsl(tlsRootCertificate);

    return new grpc.Client('peer0-org1:7051', tlsCredentials);
}
```

We then use this Gateway to create our smart contract connection:

```
private async createAndSetSmartContractConnection(organizationName: string, identityName: string, channelName: string, chaincode: string): Promise<Readonly<Contract>> {
    const gateway: Gateway = await this.createAndConnectToGateway(organizationName, identityName);
    const network: Network = gateway.getNetwork(channelName);
    const smartContract = network.getContract(chaincode);

    return smartContract;
}

private async createAndConnectToGateway(organizationName: string, identityName: string): Promise<Gateway> {
    const identityProfileFileContents: string = await new File(`${Path.toIdentityProfiles}/${identityName}.json`).getContentsAsUTF8String();
    const possibleBlockchainIdentity = JSON.parse(identityProfileFileContents) as Readonly<Record<string, unknown>>;
    const blockchainIdentity: BlockchainIdentity = new BlockchainIdentityValidator(possibleBlockchainIdentity).getValid();
    const connectionProfile: Readonly<ConnectionProfile> = await this.getConnectionProfile();

    await this.walletService.createWallet(organizationName);

    return await new GatewayFactory(this.identityService, this.signerService).createGateway(blockchainIdentity, connectionProfile);
}
```

And use this smart contract to invoke a function:

```
const proposal = contract.newProposal(invokeDTO.functionName, this.getProposalOptions(invokeDTO));

try {
  const transaction = await proposal.endorse();
  const commit = await transaction.submit();
  const status = await commit.getStatus();

  this.logger.debug(`Transaction has been submitted successfully, TxId: ${status.transactionId}, Block number: ${status.blockNumber}, Code: ${status.code}`);
} catch (error: unknown) {
  ...
}
```

As per [this package's documentation](https://hyperledger-fabric.readthedocs.io/en/release-2.4/gateway.html#retry-attempts) retries should be automatically handled when a gRPC connection error occurs, but we have not observed this behaviour and have to send the same request multiple times until it works. We have not implemented a retry mechanism ourselves.

After the first successful invoke, all the following work as expected and this error gets fixed apparently.

Is there anything we are missing somewhere, or some misconfiguration going on?

Any help would be appreciated! Please reach out if you need more details :)

Kind regards,
Isra (isrand) Nebot Dominguez

**Comment by bestbeforetoday** [comment]
The documentation you have linked to describes the behaviour of the Gateway service within the Fabric peer. During endorsement, if the Gateway service fails to connect to an endorsing peer, it will try a different peer until it runs out of peers that can be used to satisfy endorsement. If the Gateway service fails to obtain sufficient endorsements to satisfy the endorsement policy, it will return a gRPC error response with an ABORTED error code.

The UNAVAILABLE error code you are seeing suggests that your client could not connect to the Gateway service provided by the Fabric peer. This could happen for several reasons, such as a transient network outage, a Gateway peer going off-line, or a network firewall or proxy along the route to the Gateway peer closing an idle gRPC connection. The Fabric Gateway client API leaves it up to the application code how to respond to these failures. One possible response is for your application code to retry the call, either immediately or after a short delay.

In case your issues are caused by persistent gRPC connections being closed due after periods of inactivity, you might consider setting keepalive properties when creating your gRPC client:

https://github.com/grpc/grpc/blob/master/doc/keepalive.md

**Comment by bestbeforetoday** [comment]
Hopefully the clarification of behaviour above has addressed your concern. I don't see an obvious bug here that needs to be resolved. If you do see a code issue, please post another comment and we can reopen this issue.
