### ISSUE TITLE
Transient orderer error is not being retried

### ISSUE THREAD

**Issue by tskvivekmani** [hyperledger/fabric-gateway#517]
Gateway service fails to retry with orderers when it receives a response status == SERVICE_UNAVAILABLE

```
WARN [gateway] Submit -> Error sending transaction to orderer txID=<TXN_ID> endpoint=<ORDERER> err="rpc error: code = Aborted desc = received unsuccessful response from orderer: SERVICE_UNAVAILABLE"
```
 
As per this logic, when the status is != Status_SUCCESS, it return rpc error as `Aborted`…
https://github.com/hyperledger/fabric/blob/main/internal/pkg/gateway/api.go#L467-L469

Whereas the calling function will retry with the next orderer only if the code is `Unavailable`…
https://github.com/hyperledger/fabric/blob/main/internal/pkg/gateway/api.go#L444-L446

So if the intention is to retry with the next orderer, do we need to handle this status `Status_SERVICE_UNAVAILABLE` in this [condition](https://github.com/hyperledger/fabric/blob/main/internal/pkg/gateway/api.go#L467-L469)…

Ref:
Discussion thread in fabric-dev slack channel: https://ibm-blockchain.slack.com/archives/CL3L0REMD/p1671447903462259

**Comment by tskvivekmani** [comment]
Adding slack conversations here for reference:

> David Kelsey
> If the service is unavailable then it means it managed to contact the orderer. So maybe the assumption is that if that orderer states the service is unavailable then all the orderers would respond with the same. Do you have a scenario where 1 orderer responds unavailable yet the others are available ?
> 
> 
> Andrew Coleman
> It looks like the orderer returns SERVICE_UNAVAILBLE if there is an error in the consensus logic. There might be a need for different logic in the gateway.
> 
> 
> Vivekmani TSK
> In our scenario, we’re running multiple test-cases concurrently and we’re seeing this failure intermittently while other cases are succeeding…
> If the orderer failure is transient, then we expect the gateway to retry….
>
> Andrew Coleman
> can you see in the orderer logs why it is failing?
> 
> 
> Vivekmani TSK
> It failed with
>  `Rejecting broadcast of normal message from 172.30.29.163:39574 with SERVICE_UNAVAILABLE: rejected by Order: EOF`
>
Orderer logs during that timestamp for ref:
```
[orderingservice2-5b9fdbd4bd-w8cbn orderer] 2022-12-16 09:07:35.570 UTC [orderer.common.broadcast] Handle -> WARN 628f7 Error reading from 172.30.34.193:38816: rpc error: code = Canceled desc = context canceled 

[orderingservice2-5b9fdbd4bd-w8cbn orderer] 2022-12-16 09:07:35.570 UTC [comm.grpc.server] 1 -> INFO 628f8 streaming call completed grpc.service=orderer.AtomicBroadcast grpc.method=Broadcast grpc.request_deadline=2022-12-16T09:08:05.565Z grpc.peer_address=172.30.34.193:38816 grpc.peer_subject="CN=itorg1peer3,OU=peer" error="rpc error: code = Canceled desc = context canceled" grpc.code=Canceled grpc.call_duration=2.574094ms 

[orderingservice2-5b9fdbd4bd-w8cbn orderer] 2022-12-16 09:07:36.014 UTC [orderer.common.broadcast] ProcessMessage -> WARN 628f9 [channel: intg-shared-mixed] Rejecting broadcast of normal message from 172.30.29.163:39574 with SERVICE_UNAVAILABLE: rejected by Order: EOF 

[orderingservice2-5b9fdbd4bd-w8cbn orderer] 2022-12-16 09:07:36.014 UTC [comm.grpc.server] 1 -> INFO 628fa streaming call completed grpc.service=orderer.AtomicBroadcast grpc.method=Broadcast grpc.request_deadline=2022-12-16T09:08:06.012Z grpc.peer_address=172.30.29.163:39574 grpc.peer_subject="CN=itorg1peer3,OU=peer" grpc.code=OK grpc.call_duration=800.815µs
```

**Comment by bestbeforetoday** [comment]
As Dave mentioned in the chat transcript, the logic I expect is that the transaction is "bad" and rejected by the orderer, the client should get a gRPC Aborted response. If the Gateway is unable to get a "good" or "bad" status from an orderer (typically because the orderer cannot be reached) then other orderers should be tried. The legacy SDKs use similar logic:

https://github.com/hyperledger/fabric-sdk-node/blob/2eee017965721a7514c14cbae5e12d5414bc1263/fabric-common/lib/DiscoveryHandler.js#L145-L151

If there are cases where the orderer can return a non-success status code for a message that is not confirmed "bad", we need to change the Gateway peer logic to try other orderers in that case rather than immediately return a gRPC Aborted response. An orderer status code >=500 (INTERNAL_SERVER_ERROR, NOT_IMPLEMENTED, SERVICE_UNAVAILABLE) seems to fit this category as it indicated the orderer (rather than the message) is the problem. Or perhaps:

- 200 (SUCCESS) means "good" so return gRPC OK
- Status code >=400 and <500 (BAD_REQUEST, FORBIDDEN, NOT_FOUND) means "bad" so return gRPC Aborted
- Anything else (including connection failure) is neither good or bad so should try other orderers
- If we run out of orderers without getting either a "good" or "bad" status, return gRPC Unavailable

Possibly the Gateway could return a gRPC Internal (error) if no "good" or "bad" status is obtained and orderers are contactable to indicate an orderer problem and encourage clients not to simply retry, which they might reasonably do on receiving a gRPC Unavailable. On the other hand, you would hope that a system running multiple orderer nodes will have some functioning orderers so this is not an expected scenario.
